[workspace]

members = [
    "async-file",
    "async-rt",
    "io-uring-callback",
    "io-uring",
    "slab",
    "sharded-slab",
    "flume",
]

exclude = [ "sgx", "incubator-teaclave-sgx-sdk", "untrusted_allocator" ]