[package]
name = "app"
version = "1.0.0"
authors = ["The Teaclave Authors"]
build = "build.rs"

[dependencies]
sgx_types = { path = "../../incubator-teaclave-sgx-sdk/sgx_types" }
sgx_urts = { path = "../../incubator-teaclave-sgx-sdk/sgx_urts" }
libc = "0.2"
